spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate # 개발용: 테이블 자동 생성/수정
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      timeout: 2000ms


  logging:
    level:
      root: INFO                            # 전체 기본 로그 레벨
      com.example.backend: DEBUG            # 내 코드(Service, Controller 등)의 상세 로그 출력
      org.springframework.security: DEBUG    # 시큐리티 필터 체인 및 권한 확인 로그
      org.springframework.web: DEBUG         # HTTP 요청/응답 파라미터 확인
      org.hibernate.SQL: DEBUG               # 실행되는 SQL 쿼리문 출력
      org.hibernate.orm.jdbc.bind: TRACE     # SQL에 들어가는 파라미터 값(? 표시된 부분) 확인


server:
  port: 8080



# 로컬환경에서는 JWT_SECRET값은 .env 파일에서 읽는다.
jwt:
  secret: ${JWT_SECRET}