name: Deploy to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOME_SERVER_HOST }}
          username: ${{ secrets.HOME_SERVER_USER }}
          port: ${{ secrets.HOME_SERVER_PORT }}
          key: ${{ secrets.HOME_SERVER_SSH_KEY }}

          script: |
            echo "🚀 Deploy start"

            cd ~/moim_moim

            echo "📥 Git pull"
            git pull origin main

            echo "🛑 Stop containers"
            docker compose -f docker-compose.prod.yml down

            echo "⬇️ Pull latest backend image"
            docker pull qcogns97/moim-backend:latest

            echo "⬇️ Pull latest nginx image"
            docker pull qcogns97/moim-nginx:latest

            echo "▶️ Start containers"
            docker compose --env-file .env.prod -f docker-compose.prod.yml up -d

            echo "✅ Deploy finished"
